kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        oidc-issuer-url: https://dex-server.localhost:30443/dex
        oidc-client-id: YOUR_CLIENT_ID
        oidc-username-claim: email
        oidc-ca-file: /usr/local/share/ca-certificates/dex-ca.crt
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp/kubelogin-system-test-dex-ca.crt
        containerPath: /usr/local/share/ca-certificates/dex-ca.crt
    extraPortMappings:
      - containerPort: 30443
        hostPort: 30443
        listenAddress: "127.0.0.1"
        protocol: TCP
